- name: Deploy Mojo JoJo 
  hosts: dockerhosts
  vars_files:
    - mojo-vars-vault.yml
  remote_user: josiah
  tasks:
  - name: Pull latest version from github
    command: cd ~/mojojojo-bot && git pull
  - name: Build from the latest version
    command: cd ~/mojojojo-bot && docker build -t mojo -f docker/dockerfile .
  - name: Run the newly built docker container
    command: docker container run -e "SLACK_BOT_TOKEN={{ VAULT_SLACK_BOT_TOKEN }}" --restart "always" mojo 