version: '3'

services:
  sonarr:
    image: "linuxserver/sonarr"
    ports:
      - "8989:8989"
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
    volumes:
      - "/home/josiah/.config/NzbDrone:/config"
      - "/storage/private/usenet-complete/:/downloads"
      - "/storage/private/usenet-complete/tv/:/tv"
  lidarr:
    image: "linuxserver/lidarr"
    ports:
      - "8686:8686"
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
    volumes:
      - "/home/josiah/Documents/apps/Lidarr:/config"
      - "/storage/private/usenet-complete/:/downloads"
      - "/storage/private/usenet-complete/audio/:/music"

