version: '3'

services:
  sonarr:
    image: "linuxserver/sonarr"
    ports:
      - "8989:8989"
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
    volumes:
      - "/home/josiah/.config/NzbDrone:/config"
      - "/Volumes/usenet/:/downloads"
      - "/Volumes/usenet/tv/:/tv"
  lidarr:
    image: "linuxserver/lidarr"
    ports:
      - "8686:8686"
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
    volumes:
      - "/home/josiah/Documents/apps/Lidarr:/config"
      - "/Volumes/usenet/:/downloads"
      - "/Volumes/usenet/audio/:/music"
  radarr:
    image: "linuxserver/radarr"
    ports:
      - "7878:7878"
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
    volumes:
      - "/home/josiah/Documents/apps/radarr:/config"
      - "/Volumes/usenet/:/downloads"
      - "/Volumes/usenet/movies/:/music"
  sabnzb:
    image: "linuxserver/sabnzbd"
    ports:
      - "8080:8080"
      - "9090:9090"
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
    volumes:
      - "/home/josiah/Documents/apps/sabnzbd:/config"
      - "/Volumes/usenet/:/downloads"
      - "/Volumes/usenet/audio/:/music"

