- name: Copy splunk modules to corp deploy server
  hosts: corp
#  vars_files:
#    - mojo-vars-vault.yml
  remote_user: josiah_ledbetter
  tasks:
  - name: Copy item to remote server
    copy: 
      # make sure the permissions of the file you are copying are readable by ansible user
      src: /Users/josiah_ledbetter/Documents/projects/splunk/configs/filething/
      # src must not end in "/" or it will only copy files inside dir instead of entire dir
      dest: /opt/splunk/temp/
      owner: splunk
      group: splunk
    # these below affect the entire task, and should not go under the command's indention level. This took WAY too longer to figure out.
    become: "true"
    become_method: sudo
    become_user: root
