all:
  children:
    dockerhosts:
      hosts:
        awful-1.awful.club:
      vars:
        ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ansible@ssh.awful.club"'
    macs:
      hosts:
        hydra-ling:
    windows:
      hosts:
        lurker-ling:
    linux:
      hosts:
        ling-bane:
