all:
  children:
    dockerhosts:
      hosts:
        awful-1.awful.club:
    macs:
      hosts:
        hydra-ling:
    windows:
      hosts:
        lurker-ling:
    linux:
      hosts:
        ling-bane:
